sane defaults even without config files
https://phabricator.whonix.org/T286
https://phabricator.whonix.org/T503

diff --git a/usr/lib/uwtwrapper b/usr/lib/uwtwrapper
--- a/usr/lib/uwtwrapper
+++ b/usr/lib/uwtwrapper
@@ -197,10 +197,62 @@ if [ ! -e "$uwtwrapper_parent.anondist-orig" ]; then
 fi
 ## }}}
 
-## Files in /etc/uwt.d/* set variables such as
-## port_aptget, port_gpg, ... and variables such as
-## timeprivacy_aptget, timeprivacy_gpg, ... and variables such as
-## uwtwrapper_aptget, uwtwrapper_gpg, ... and ip.
+declare -A -g timeprivacy
+declare -A -g uwtwrapper
+declare -A -g uwtport
+
+[ -n "$timeprivacy_global" ] || timeprivacy_global="0"
+[ -n "$uwtwrapper_global" ] || uwtwrapper_global="1"
+
+[ -n "$uwtport" ] || uwtport["/usr/bin/git"]="9107"
+[ -n "$uwtport" ] || uwtport["/usr/bin/apt-get"]="9104"
+[ -n "$uwtport" ] || uwtport["/usr/bin/curl"]="9117"
+[ -n "$uwtport" ] || uwtport["/usr/bin/gpg"]="9105"
+[ -n "$uwtport" ] || uwtport["/usr/bin/mixmaster-update"]="9120"
+[ -n "$uwtport" ] || uwtport["/usr/bin/rawdog"]="9118"
+[ -n "$uwtport" ] || uwtport["/usr/bin/ssh"]="9106"
+[ -n "$uwtport" ] || uwtport["/usr/bin/wget"]="9109"
+[ -n "$uwtport" ] || uwtport["/usr/bin/aptitude-curses"]="9124"
+[ -n "$uwtport" ] || uwtport["/usr/bin/yum"]="9125"
+[ -n "$uwtport" ] || uwtport["/usr/bin/yumdownloader"]="9125"
+
+settings_detection() {
+   if [ "$UWT_DEV_PASSTHROUGH" = "1" ]; then
+      ## Can be the case when building Whonix from source code.
+      GATEWAY_IP="UWT_DEV_PASSTHROUGH"
+      return 0
+   fi
+
+   if command -v qubesdb-read >/dev/null 2>&1 ; then
+      ## '/qubes-vm-type' is either 'AppVM', 'ProxyVM', 'NetVM' or 'TemplateVM'
+      qubes_vm_type="$(qubesdb-read /qubes-vm-type)"
+      if [ "$qubes_vm_type" = "TemplateVM" ] || [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
+         ## 'qubesdb-read /qubes-gateway' could fail if NetVM is set to 'none'.
+         GATEWAY_IP="$(qubesdb-read /qubes-gateway 2>/dev/null)" || { GATEWAY_IP_ERROR="qubesdb_read_failed"; GATEWAY_IP="127.0.0.1"; };
+         return 0
+      fi
+   fi
+
+   if [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
+      GATEWAY_IP="10.152.152.10"
+      return 0
+   fi
+
+   if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
+      GATEWAY_IP="127.0.0.1"
+      return 0
+   fi
+
+   error "\
+uwt wrapper could not determine if this is Whonix-Workstation or Whonix-Gateway.
+Variable GATEWAY_IP does not exist early enough in /etc/uwt.d.
+If you are using a Custom-Workstation, please consider installing the
+anon-gw-base-files or anon-ws-base-files package.
+If you are not using a Custom-Workstation: please report this bug!"
+}
+
+settings_detection
+
 shopt -s nullglob
 for i in /etc/uwt.d/*.conf; do
    bash -n "$i"
